#!/bin/bash

# A script that will ask for a number and print out a message depending on the value. 

read -p "Enter a value: " n

case $n in
    1|2)
        if [ $n -eq 1 ]
        then
            echo "One"
        else
            echo "Two"
        fi
    ;;
    [3-9])
        echo "Between 3 and 9";;
    ??)
        echo "Two characters";;
    *)
        echo "Unkown :("
esac
    