#!/bin/bash

#check-even 5 => This is an error, you can't call a function before declaring it.

check_even () {
   #This is a local variable, meaning we can't access it from outside this function
	local mod=2
	#echo "The value of mod is $mod"
	if [ $(("$1" % $mod)) -eq 0 ]
	then
	   echo "The number $1 is even!";
	else 
	   echo "The number $1 is odd!"
	fi
}


read -p "Introduce a number: " number
check_even $number
#echo "This is mod: $mod"